<a href="https://colab.research.google.com/github/pranjaltiwari8081-lab/EDA/blob/main/loan_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [94]:
data = pd.read_csv('loan.csv')
data.head()

loan_id   no_of_dependents      education  self_employed   income_annum  \
0        1                  2       Graduate             No        9600000   
1        2                  0   Not Graduate            Yes        4100000   
2        3                  3       Graduate             No        9100000   
3        4                  3       Graduate             No        8200000   
4        5                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   
3                   3300000              23300000            7900000   
4                   8200000              29400000            5000000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected  
3     Rejected  
4     Rejected

In [95]:
data = data.drop('loan_id', axis=1)
data = data.drop(' no_of_dependents', axis=1)
data = data.drop(' self_employed', axis=1)
data = data.drop(' income_annum', axis=1)
data = data.drop(' residential_assets_value', axis=1)
data = data.drop(' loan_term', axis=1)
data = data.drop(' luxury_assets_value', axis=1)
data = data.drop(' bank_asset_value', axis=1)
data.head()


education  loan_amount  cibil_score  commercial_assets_value  \
0       Graduate     29900000          778                 17600000   
1   Not Graduate     12200000          417                  2200000   
2       Graduate     29700000          506                  4500000   
3       Graduate     30700000          467                  3300000   
4   Not Graduate     24200000          382                  8200000   

  loan_status  
0    Approved  
1    Rejected  
2    Rejected  
3    Rejected  
4    Rejected

In [96]:
le = LabelEncoder()
data[' loan_status'] = le.fit_transform(data[' loan_status'])

In [97]:
X = data[[' cibil_score',' commercial_assets_value',' loan_amount']]
y = data[[' loan_status']]


In [98]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print ( X_train)

      cibil_score  commercial_assets_value  loan_amount
1675          568                 13900000     29900000
1164          710                 10300000     34000000
192           682                  1100000      2900000
910           754                  3300000     13100000
567           441                  2500000     11100000
...           ...                      ...          ...
3444          530                  1000000      4700000
466           411                   500000      1800000
3092          449                 10600000     20600000
3772          541                  1300000     21400000
860           837                  3700000     17300000

[3415 rows x 3 columns]


In [99]:
 scaler = StandardScaler()
 X_train = scaler.fit_transform(X_train)
 X_test = scaler.transform(X_test)

In [100]:
 model = LogisticRegression()
 model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [101]:
ypred = model.predict(X_test)
print(ypred)

[1 0 1 0 0 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0
 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0
 1 0 1 1 0 0 1 1 1 0 1 1 0 0 1 1 0 1 0 1 1 0 1 0 0 1 0 1 0 1 1 0 1 0 0 0 0
 0 1 1 0 1 0 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1 1 0 1 0
 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 1 1
 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 1 1 1 0 1
 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0
 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 0
 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 1 1 0 0 0 1 1 1 0 1 0 0 1 1 1 0 0 0
 0 1 0 1 1 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1
 1 0 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 1 1 0 0 1 0 0 1
 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 1 0 0 0
 0 1 0 0 0 0 0 1 1 0 1 1 

In [102]:
 accuracy_score(y_test, ypred)

0.9285714285714286

In [103]:
confusion_matrix(y_test, ypred)

array([[502,  34],
       [ 27, 291]])

In [104]:
print ( X_train)

[[-0.18740061  2.04678575  1.62477248]
 [ 0.63739678  1.22311091  2.07712843]
 [ 0.47476068 -0.8818359  -1.35415691]
 ...
 [-0.87860405  1.29175048  0.5986968 ]
 [-0.34422828 -0.83607619  0.68696138]
 [ 1.37506769 -0.28695963  0.23460543]]
